name = "songbook-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "songbook-db"
database_id = "7c59baba-35fe-4bc6-b7f4-dba945b5901b"
